### PR TITLE
Samonte Task Performance

### PR DESCRIPTION
**Pull request by Samonte21**

### CODE REVIEW

**Review by Samonte21 — COMMENTED** [review]
[Task Performance_Samonte.txt](https://github.com/jeanoskii/Software-Design-Prefinal-Exam/files/7731690/Task.Performance_Samonte.txt)

**Comment by Samonte21** [comment]
[Task Performance_Samonte.txt](https://github.com/jeanoskii/Software-Design-Prefinal-Exam/files/7731710/Task.Performance_Samonte.txt)

**Comment by jeanoskii** [comment]
Please add only 1 section/entry about yourself. Please remove the other entries.

**Review by jeanoskii — APPROVED** [review]
approved

**Pull request merged**
